// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfsF_L92zitAJbKicjW1p8lAYBkJ0nCg',
    appId: '1:793070399680:web:0c2731c567736c2188fd25',
    messagingSenderId: '793070399680',
    projectId: 'quiz-in405109',
    authDomain: 'quiz-in405109.firebaseapp.com',
    storageBucket: 'quiz-in405109.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67i0RPg_tZq2Pd8VL-EhJH_0IX2KzDuQ',
    appId: '1:793070399680:android:4d0fe4f1dc2fa31c88fd25',
    messagingSenderId: '793070399680',
    projectId: 'quiz-in405109',
    storageBucket: 'quiz-in405109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBghY5LvLNEtowcoPTchC4pnEXJAywZNlM',
    appId: '1:793070399680:ios:049a5cb0b5047c0188fd25',
    messagingSenderId: '793070399680',
    projectId: 'quiz-in405109',
    storageBucket: 'quiz-in405109.appspot.com',
    iosBundleId: 'com.example.quizIn405109',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBghY5LvLNEtowcoPTchC4pnEXJAywZNlM',
    appId: '1:793070399680:ios:049a5cb0b5047c0188fd25',
    messagingSenderId: '793070399680',
    projectId: 'quiz-in405109',
    storageBucket: 'quiz-in405109.appspot.com',
    iosBundleId: 'com.example.quizIn405109',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXfsF_L92zitAJbKicjW1p8lAYBkJ0nCg',
    appId: '1:793070399680:web:6c237b39cb5264ad88fd25',
    messagingSenderId: '793070399680',
    projectId: 'quiz-in405109',
    authDomain: 'quiz-in405109.firebaseapp.com',
    storageBucket: 'quiz-in405109.appspot.com',
  );
}
